# UAPI Header export list

ifeq ($(wildcard $(srctree)/arch/$(SRCARCH)/include/uapi/asm/a.out.h),)
no-export-headers += a.out.h
endif

ifeq ($(wildcard $(srctree)/arch/$(SRCARCH)/include/uapi/asm/kvm.h),)
no-export-headers += kvm.h
endif

ifeq ($(wildcard $(srctree)/arch/$(SRCARCH)/include/uapi/asm/kvm_para.h),)
no-export-headers += kvm_para.h
endif

no-export-headers += batman_adv.h
no-export-headers += dma-buf.h
no-export-headers += hash_info.h
no-export-headers += tee.h
no-export-headers += userio.h

ifneq ($(VSERVICES_SUPPORT), "")
include include/linux/Kbuild.vservices
endif
header-y += auto_dev-ioctl.h
header-y += bcache.h
header-y += btrfs_tree.h
header-y += coresight-stm.h
header-y += cryptouser.h
header-y += hash_info.h
header-y += kcm.h
header-y += kcov.h
header-y += kfd_ioctl.h
header-y += lightnvm.h
header-y += module.h
header-y += nilfs2_api.h
header-y += nilfs2_ondisk.h
header-y += nsfs.h
header-y += pr.h
header-y += qrtr.h
header-y += stm.h
header-y += wil6210_uapi.h
header-y += cifs/
header-y += genwqe/
